# Generated by Django 3.2.13 on 2022-04-16 05:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsForTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='введите наименование товара с сайта wildberries для отслежения цен')),
                ('articul', models.PositiveIntegerField(verbose_name='введите артикул товара с сайта wildberries')),
            ],
        ),
        migrations.CreateModel(
            name='MyTrackedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='полное наименование товара')),
                ('articul', models.PositiveIntegerField(verbose_name='артикул')),
                ('brand_name', models.CharField(max_length=32, verbose_name='брэнд')),
                ('price', models.PositiveSmallIntegerField(verbose_name='цена товара')),
                ('discount_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='цена товара со скидкой')),
                ('date_field', models.DateTimeField(default=datetime.datetime(2022, 4, 16, 5, 59, 2, 453683, tzinfo=utc), verbose_name='дата время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_interval', models.CharField(choices=[(3600, '1 hour'), (43200, '12 hours'), (86400, '24 hours')], max_length=3, verbose_name='выберите интервал отслеживания цен')),
                ('start_date', models.DateField(default=datetime.datetime(2022, 4, 16, 5, 59, 2, 457708, tzinfo=utc))),
                ('parse_till_date', models.DateField(blank=True, help_text='поле может быть пустым', null=True, verbose_name='введите дату окончания отслежения')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.goodsfortracking', verbose_name='выберите товар для отслеживания цен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
