# Generated by Django 5.0.6 on 2024-07-09 00:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsForTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        verbose_name="введите наименование товара с сайта wildberries для отслежения цен",
                    ),
                ),
                (
                    "articul",
                    models.PositiveIntegerField(
                        verbose_name="введите артикул товара с сайта wildberries"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyTasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "set_interval",
                    models.CharField(
                        choices=[
                            (3600, "1 hour"),
                            (43200, "12 hours"),
                            (86400, "24 hours"),
                            (30, "30 sec test"),
                        ],
                        max_length=15,
                        verbose_name="выберите интервал отслеживания",
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "parse_till_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="поле может быть пустым",
                        null=True,
                        verbose_name="введите дату окончания отслеживания",
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.goodsfortracking",
                        verbose_name="выберите товар для отслеживания",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyTrackedGoods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="полное наименование товара"
                    ),
                ),
                ("articul", models.PositiveIntegerField(verbose_name="артикул")),
                ("brand_name", models.CharField(max_length=32, verbose_name="брэнд")),
                ("price", models.PositiveSmallIntegerField(verbose_name="цена товара")),
                (
                    "discount_price",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="цена товара со скидкой"
                    ),
                ),
                (
                    "date_field",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="дата время"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
