# Generated by Django 5.0.6 on 2024-07-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mytasks",
            name="set_interval",
            field=models.CharField(
                choices=[
                    (3600, "1 hour"),
                    (43200, "12 hours"),
                    (86400, "24 hours"),
                    (180, "3 min test"),
                ],
                max_length=15,
                verbose_name="выберите интервал отслеживания",
            ),
        ),
    ]
