# Generated by Django 4.2 on 2024-12-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_mytasks_set_interval"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsfortracking",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="mytrackedgoods",
            name="discount_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="цена товара со скидкой"
            ),
        ),
        migrations.AlterField(
            model_name="mytrackedgoods",
            name="price",
            field=models.PositiveIntegerField(verbose_name="цена товара"),
        ),
    ]
