# Generated by Django 3.2.13 on 2022-04-16 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220416_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytasks',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
