# Generated by Django 3.2.13 on 2022-04-16 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mytasks_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytasks',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.goodsfortracking', verbose_name='выберите товар для отслеживания'),
        ),
        migrations.AlterField(
            model_name='mytasks',
            name='parse_till_date',
            field=models.DateTimeField(blank=True, help_text='поле может быть пустым', null=True, verbose_name='введите дату окончания отслеживания'),
        ),
        migrations.AlterField(
            model_name='mytasks',
            name='set_interval',
            field=models.CharField(choices=[(3600, '1 hour'), (43200, '12 hours'), (86400, '24 hours')], max_length=3, verbose_name='выберите интервал отслеживания'),
        ),
        migrations.AlterField(
            model_name='mytasks',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
