# Generated by Django 3.2.13 on 2022-04-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220416_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytasks',
            name='set_interval',
            field=models.CharField(choices=[(3600, '1 hour'), (43200, '12 hours'), (86400, '24 hours'), (30, '30 sec test')], max_length=15, verbose_name='выберите интервал отслеживания'),
        ),
    ]
